charmap "ガ", $05
charmap "ギ", $06
charmap "グ", $07
charmap "ゲ", $08
charmap "ゴ", $09
charmap "ザ", $0A
charmap "ジ", $0B
charmap "ズ", $0C
charmap "ゼ", $0D
charmap "ゾ", $0E
charmap "ダ", $0F
charmap "ヂ", $10
charmap "ヅ", $11
charmap "デ", $12
charmap "ド", $13
charmap "バ", $19
charmap "ビ", $1A
charmap "ブ", $1B
charmap "ボ", $1C
charmap "が", $26
charmap "ぎ", $27
charmap "ぐ", $28
charmap "げ", $29
charmap "ご", $2A
charmap "ざ", $2B
charmap "じ", $2C
charmap "ず", $2D
charmap "ぜ", $2E
charmap "ぞ", $2F
charmap "だ", $30
charmap "ぢ", $31
charmap "づ", $32
charmap "で", $33
charmap "ど", $34
charmap "ば", $3A
charmap "び", $3B
charmap "ぶ", $3C
charmap "べ", $3D
charmap "ぼ", $3E
charmap "パ", $40
charmap "ピ", $41
charmap "プ", $42
charmap "ポ", $43
charmap "ぱ", $44
charmap "ぴ", $45
charmap "ぷ", $46
charmap "ぺ", $47
charmap "ぽ", $48
charmap "ア", $80
charmap "イ", $81
charmap "ウ", $82
charmap "エ", $83
charmap "ォ", $84
charmap "カ", $85
charmap "キ", $86
charmap "ク", $87
charmap "ケ", $88
charmap "コ", $89
charmap "サ", $8A
charmap "シ", $8B
charmap "ス", $8C
charmap "セ", $8D
charmap "ソ", $8E
charmap "タ", $8F
charmap "チ", $90
charmap "ツ", $91
charmap "テ", $92
charmap "ト", $93
charmap "ナ", $94
charmap "ニ", $95
charmap "ヌ", $96
charmap "ネ", $97
charmap "ノ", $98
charmap "ハ", $99
charmap "ヒ", $9A
charmap "フ", $9B
charmap "ホ", $9C
charmap "マ", $9D
charmap "ミ", $9E
charmap "ム", $9F
charmap "メ", $A0
charmap "モ", $A1
charmap "ヤ", $A2
charmap "ユ", $A3
charmap "ヨ", $A4
charmap "ラ", $A5
charmap "ル", $A6
charmap "レ", $A7
charmap "ロ", $A8
charmap "ワ", $A9
charmap "ヲ", $AA
charmap "ン", $AB
charmap "ッ", $AC
charmap "ャ", $AD
charmap "ュ", $AE
charmap "ョ", $AF
charmap "ィ", $B0
charmap "あ", $B1
charmap "い", $B2
charmap "う", $B3
charmap "え", $B4
charmap "お", $B5
charmap "か", $B6
charmap "き", $B7
charmap "く", $B8
charmap "け", $B9
charmap "こ", $BA
charmap "さ", $BB
charmap "し", $BC
charmap "す", $BD
charmap "せ", $BE
charmap "そ", $BF
charmap "た", $C0
charmap "ち", $C1
charmap "つ", $C2
charmap "て", $C3
charmap "と", $C4
charmap "な", $C5
charmap "に", $C6
charmap "ぬ", $C7
charmap "ね", $C8
charmap "の", $C9
charmap "は", $CA
charmap "ひ", $CB
charmap "ふ", $CC
charmap "へ", $CD
charmap "ほ", $CE
charmap "ま", $CF
charmap "み", $D0
charmap "む", $D1
charmap "め", $D2
charmap "も", $D3
charmap "や", $D4
charmap "ゆ", $D5
charmap "よ", $D6
charmap "ら", $D7
charmap "り", $D8
charmap "る", $D9
charmap "れ", $DA
charmap "ろ", $DB
charmap "わ", $DC
charmap "を", $DD
charmap "ん", $DE
charmap "っ", $DF
charmap "ゃ", $E0
charmap "ゅ", $E1
charmap "ょ", $E2
charmap "ー", $E3

charmap "<pkmn>", $4A ; PkMn
charmap "@", $50
charmap "<PLAYER>", $52
charmap "<RIVAL>", $53
charmap "#", $54
;charmap "POKé", $54
charmap "<TARGET>", $59
charmap "<USER>", $5A
charmap "′", $71
charmap "″", $73
charmap "№", $74
charmap "…", $75

charmap "┌", $79
charmap "─", $7A
charmap "┐", $7B
charmap "│", $7C
charmap "└", $7D
charmap "┘", $7E

charmap " ", $7F
charmap "A", $80
charmap "B", $81
charmap "C", $82
charmap "D", $83
charmap "E", $84
charmap "F", $85
charmap "G", $86
charmap "H", $87
charmap "I", $88
charmap "J", $89
charmap "K", $8A
charmap "L", $8B
charmap "M", $8C
charmap "N", $8D
charmap "O", $8E
charmap "P", $8F
charmap "Q", $90
charmap "R", $91
charmap "S", $92
charmap "T", $93
charmap "U", $94
charmap "V", $95
charmap "W", $96
charmap "X", $97
charmap "Y", $98
charmap "Z", $99

charmap "a", $A0
charmap "b", $A1
charmap "c", $A2
charmap "d", $A3
charmap "e", $A4
charmap "f", $A5
charmap "g", $A6
charmap "h", $A7
charmap "i", $A8
charmap "j", $A9
charmap "k", $AA
charmap "l", $AB
charmap "m", $AC
charmap "n", $AD
charmap "o", $AE
charmap "p", $AF
charmap "q", $B0
charmap "r", $B1
charmap "s", $B2
charmap "t", $B3
charmap "u", $B4
charmap "v", $B5
charmap "w", $B6
charmap "x", $B7
charmap "y", $B8
charmap "z", $B9

charmap "é", $D0
charmap "'d", $D1
charmap "'l", $D2
charmap "'s", $D3
charmap "'t", $D4
charmap "'v", $D5
charmap "'r", $D6
charmap "'m", $D7
charmap "𝗟", $D8
charmap "(", $D9
charmap ")", $DA
charmap ":", $DB
charmap ";", $DC
charmap "[", $DD
charmap "]", $DE
charmap "*", $DF

charmap "'", $E0

charmap "-", $E3
charmap "+", $E4
charmap "&", $E5
charmap "?", $E6
charmap "!", $E7
charmap ".", $E8

charmap "%", $EA
charmap "𝗣", $EB
charmap "▷", $EC
charmap "▶", $ED
charmap "▲", $ED
charmap "▼", $EE
charmap "♂", $EF

charmap "¥", $F0
charmap "×", $F1
charmap "⠄", $F2
charmap "/", $F3
charmap ",", $F4
charmap "♀", $F5
charmap "0", $F6
charmap "1", $F7
charmap "2", $F8
charmap "3", $F9
charmap "4", $FA
charmap "5", $FB
charmap "6", $FC
charmap "7", $FD
charmap "8", $FE
charmap "9", $FF
