const_def
map_const PALLET_TOWN,                 9, 10 ; $00
map_const VIRIDIAN_CITY,              18, 20 ; $01
map_const PEWTER_CITY,                18, 20 ; $02
map_const CERULEAN_CITY,              18, 20 ; $03
map_const LAVENDER_TOWN,               9, 10 ; $04
map_const VERMILION_CITY,             18, 20 ; $05
map_const CELADON_CITY,               18, 25 ; $06
map_const FUCHSIA_CITY,               18, 20 ; $07
map_const CINNABAR_ISLAND,             9, 10 ; $08
map_const INDIGO_PLATEAU,              9, 10 ; $09
map_const SAFFRON_CITY,               18, 20 ; $0A
map_const UNUSED_MAP_0B,               0,  0 ; $0B
map_const ROUTE_1,                    18, 10 ; $0C
map_const ROUTE_2,                    36, 10 ; $0D
map_const ROUTE_3,                     9, 35 ; $0E
map_const ROUTE_4,                     9, 45 ; $0F
map_const ROUTE_5,                    18, 10 ; $10
map_const ROUTE_6,                    18, 10 ; $11
map_const ROUTE_7,                     9, 10 ; $12
map_const ROUTE_8,                     9, 30 ; $13
map_const ROUTE_9,                     9, 30 ; $14
map_const ROUTE_10,                   36, 10 ; $15
map_const ROUTE_11,                    9, 30 ; $16
map_const ROUTE_12,                   54, 10 ; $17
map_const ROUTE_13,                    9, 30 ; $18
map_const ROUTE_14,                   27, 10 ; $19
map_const ROUTE_15,                    9, 30 ; $1A
map_const ROUTE_16,                    9, 20 ; $1B
map_const ROUTE_17,                   72, 10 ; $1C
map_const ROUTE_18,                    9, 25 ; $1D
map_const ROUTE_19,                   27, 10 ; $1E
map_const ROUTE_20,                    9, 50 ; $1F
map_const ROUTE_21,                   45, 10 ; $20
map_const ROUTE_22,                    9, 20 ; $21
map_const ROUTE_23,                   72, 10 ; $22
map_const ROUTE_24,                   18, 10 ; $23
map_const ROUTE_25,                    9, 30 ; $24
map_const REDS_HOUSE_1F,               4,  4 ; $25
map_const REDS_HOUSE_2F,               4,  4 ; $26
map_const BLUES_HOUSE,                 4,  4 ; $27
map_const OAKS_LAB,                    6,  5 ; $28
map_const VIRIDIAN_POKECENTER,         4,  7 ; $29
map_const VIRIDIAN_MART,               4,  4 ; $2A
map_const VIRIDIAN_SCHOOL,             4,  4 ; $2B
map_const VIRIDIAN_HOUSE,              4,  4 ; $2C
map_const VIRIDIAN_GYM,                9, 10 ; $2D
map_const DIGLETTS_CAVE_EXIT,          4,  4 ; $2E
map_const VIRIDIAN_FOREST_EXIT,        4,  5 ; $2F
map_const ROUTE_2_HOUSE,               4,  4 ; $30
map_const ROUTE_2_GATE,                4,  5 ; $31
map_const VIRIDIAN_FOREST_ENTRANCE,    4,  5 ; $32
map_const VIRIDIAN_FOREST,            24, 17 ; $33
map_const MUSEUM_1F,                   4, 10 ; $34
map_const MUSEUM_2F,                   4,  7 ; $35
map_const PEWTER_GYM,                  7,  5 ; $36
map_const PEWTER_HOUSE_1,              4,  4 ; $37
map_const PEWTER_MART,                 4,  4 ; $38
map_const PEWTER_HOUSE_2,              4,  4 ; $39
map_const PEWTER_POKECENTER,           4,  7 ; $3A
map_const MT_MOON_1,                  18, 20 ; $3B
map_const MT_MOON_2,                  14, 14 ; $3C
map_const MT_MOON_3,                  18, 20 ; $3D
map_const TRASHED_HOUSE,               4,  4 ; $3E
map_const CERULEAN_HOUSE_1,            4,  4 ; $3F
map_const CERULEAN_POKECENTER,         4,  7 ; $40
map_const CERULEAN_GYM,                7,  5 ; $41
map_const BIKE_SHOP,                   4,  4 ; $42
map_const CERULEAN_MART,               4,  4 ; $43
map_const MT_MOON_POKECENTER,          4,  7 ; $44
map_const TRASHED_HOUSE_COPY,          4,  4 ; $45
map_const ROUTE_5_GATE,                3,  4 ; $46
map_const PATH_ENTRANCE_ROUTE_5,       4,  4 ; $47
map_const DAYCAREM,                    4,  4 ; $48
map_const ROUTE_6_GATE,                3,  4 ; $49
map_const PATH_ENTRANCE_ROUTE_6,       4,  4 ; $4A
map_const PATH_ENTRANCE_ROUTE_6_COPY,  4,  4 ; $4B
map_const ROUTE_7_GATE,                4,  3 ; $4C
map_const PATH_ENTRANCE_ROUTE_7,       4,  4 ; $4D
map_const PATH_ENTRANCE_ROUTE_7_COPY,  4,  4 ; $4E
map_const ROUTE_8_GATE,                4,  3 ; $4F
map_const PATH_ENTRANCE_ROUTE_8,       4,  4 ; $50
map_const ROCK_TUNNEL_POKECENTER,      4,  7 ; $51
map_const ROCK_TUNNEL_1,              18, 20 ; $52
map_const POWER_PLANT,                18, 20 ; $53
map_const ROUTE_11_GATE_1F,            5,  4 ; $54
map_const DIGLETTS_CAVE_ENTRANCE,      4,  4 ; $55
map_const ROUTE_11_GATE_2F,            4,  4 ; $56
map_const ROUTE_12_GATE_1F,            4,  5 ; $57
map_const BILLS_HOUSE,                 4,  4 ; $58
map_const VERMILION_POKECENTER,        4,  7 ; $59
map_const POKEMON_FAN_CLUB,            4,  4 ; $5A
map_const VERMILION_MART,              4,  4 ; $5B
map_const VERMILION_GYM,               9,  5 ; $5C
map_const VERMILION_HOUSE_1,           4,  4 ; $5D
map_const VERMILION_DOCK,              6, 14 ; $5E
map_const SS_ANNE_1,                   9, 20 ; $5F
map_const SS_ANNE_2,                   9, 20 ; $60
map_const SS_ANNE_3,                   3, 10 ; $61
map_const SS_ANNE_4,                   4, 15 ; $62
map_const SS_ANNE_5,                   7, 10 ; $63
map_const SS_ANNE_6,                   8,  7 ; $64
map_const SS_ANNE_7,                   4,  3 ; $65
map_const SS_ANNE_8,                   8, 12 ; $66
map_const SS_ANNE_9,                   8, 12 ; $67
map_const SS_ANNE_10,                  8, 12 ; $68
map_const UNUSED_MAP_69,               0,  0 ; $69
map_const UNUSED_MAP_6A,               0,  0 ; $6A
map_const UNUSED_MAP_6B,               0,  0 ; $6B
map_const VICTORY_ROAD_1,              9, 10 ; $6C
map_const UNUSED_MAP_6D,               0,  0 ; $6D
map_const UNUSED_MAP_6E,               0,  0 ; $6E
map_const UNUSED_MAP_6F,               0,  0 ; $6F
map_const UNUSED_MAP_70,               0,  0 ; $70
map_const LANCES_ROOM,                13, 13 ; $71
map_const UNUSED_MAP_72,               0,  0 ; $72
map_const UNUSED_MAP_73,               0,  0 ; $73
map_const UNUSED_MAP_74,               0,  0 ; $74
map_const UNUSED_MAP_75,               0,  0 ; $75
map_const HALL_OF_FAME,                4,  5 ; $76
map_const UNDERGROUND_PATH_NS,        24,  4 ; $77
map_const CHAMPIONS_ROOM,              4,  4 ; $78
map_const UNDERGROUND_PATH_WE,         4, 25 ; $79
map_const CELADON_MART_1,              4, 10 ; $7A
map_const CELADON_MART_2,              4, 10 ; $7B
map_const CELADON_MART_3,              4, 10 ; $7C
map_const CELADON_MART_4,              4, 10 ; $7D
map_const CELADON_MART_ROOF,           4, 10 ; $7E
map_const CELADON_MART_ELEVATOR,       2,  2 ; $7F
map_const CELADON_MANSION_1,           6,  4 ; $80
map_const CELADON_MANSION_2,           6,  4 ; $81
map_const CELADON_MANSION_3,           6,  4 ; $82
map_const CELADON_MANSION_4,           6,  4 ; $83
map_const CELADON_MANSION_5,           4,  4 ; $84
map_const CELADON_POKECENTER,          4,  7 ; $85
map_const CELADON_GYM,                 9,  5 ; $86
map_const GAME_CORNER,                 9, 10 ; $87
map_const CELADON_MART_5,              4, 10 ; $88
map_const CELADON_PRIZE_ROOM,          4,  5 ; $89
map_const CELADON_DINER,               4,  5 ; $8A
map_const CELADON_HOUSE,               4,  4 ; $8B
map_const CELADON_HOTEL,               4,  7 ; $8C
map_const LAVENDER_POKECENTER,         4,  7 ; $8D
map_const POKEMONTOWER_1,              9, 10 ; $8E
map_const POKEMONTOWER_2,              9, 10 ; $8F
map_const POKEMONTOWER_3,              9, 10 ; $90
map_const POKEMONTOWER_4,              9, 10 ; $91
map_const POKEMONTOWER_5,              9, 10 ; $92
map_const POKEMONTOWER_6,              9, 10 ; $93
map_const POKEMONTOWER_7,              9, 10 ; $94
map_const LAVENDER_HOUSE_1,            4,  4 ; $95
map_const LAVENDER_MART,               4,  4 ; $96
map_const LAVENDER_HOUSE_2,            4,  4 ; $97
map_const FUCHSIA_MART,                4,  4 ; $98
map_const FUCHSIA_HOUSE_1,             4,  4 ; $99
map_const FUCHSIA_POKECENTER,          4,  7 ; $9A
map_const FUCHSIA_HOUSE_2,             4,  5 ; $9B
map_const SAFARI_ZONE_ENTRANCE,        3,  4 ; $9C
map_const FUCHSIA_GYM,                 9,  5 ; $9D
map_const FUCHSIA_MEETING_ROOM,        4,  7 ; $9E
map_const SEAFOAM_ISLANDS_2,           9, 15 ; $9F
map_const SEAFOAM_ISLANDS_3,           9, 15 ; $A0
map_const SEAFOAM_ISLANDS_4,           9, 15 ; $A1
map_const SEAFOAM_ISLANDS_5,           9, 15 ; $A2
map_const VERMILION_HOUSE_2,           4,  4 ; $A3
map_const FUCHSIA_HOUSE_3,             4,  4 ; $A4
map_const MANSION_1,                  14, 15 ; $A5
map_const CINNABAR_GYM,                9, 10 ; $A6
map_const CINNABAR_LAB_1,              4,  9 ; $A7
map_const CINNABAR_LAB_2,              4,  4 ; $A8
map_const CINNABAR_LAB_3,              4,  4 ; $A9
map_const CINNABAR_LAB_4,              4,  4 ; $AA
map_const CINNABAR_POKECENTER,         4,  7 ; $AB
map_const CINNABAR_MART,               4,  4 ; $AC
map_const CINNABAR_MART_COPY,          4,  4 ; $AD
map_const INDIGO_PLATEAU_LOBBY,        6,  8 ; $AE
map_const COPYCATS_HOUSE_1F,           4,  4 ; $AF
map_const COPYCATS_HOUSE_2F,           4,  4 ; $B0
map_const FIGHTING_DOJO,               6,  5 ; $B1
map_const SAFFRON_GYM,                 9, 10 ; $B2
map_const SAFFRON_HOUSE_1,             4,  4 ; $B3
map_const SAFFRON_MART,                4,  4 ; $B4
map_const SILPH_CO_1F,                 9, 15 ; $B5
map_const SAFFRON_POKECENTER,          4,  7 ; $B6
map_const SAFFRON_HOUSE_2,             4,  4 ; $B7
map_const ROUTE_15_GATE_1F,            5,  4 ; $B8
map_const ROUTE_15_GATE_2F,            4,  4 ; $B9
map_const ROUTE_16_GATE_1F,            7,  4 ; $BA
map_const ROUTE_16_GATE_2F,            4,  4 ; $BB
map_const ROUTE_16_HOUSE,              4,  4 ; $BC
map_const ROUTE_12_HOUSE,              4,  4 ; $BD
map_const ROUTE_18_GATE_1F,            5,  4 ; $BE
map_const ROUTE_18_GATE_2F,            4,  4 ; $BF
map_const SEAFOAM_ISLANDS_1,           9, 15 ; $C0
map_const ROUTE_22_GATE,               4,  5 ; $C1
map_const VICTORY_ROAD_2,              9, 15 ; $C2
map_const ROUTE_12_GATE_2F,            4,  4 ; $C3
map_const VERMILION_HOUSE_3,           4,  4 ; $C4
map_const DIGLETTS_CAVE,              18, 20 ; $C5
map_const VICTORY_ROAD_3,              9, 15 ; $C6
map_const ROCKET_HIDEOUT_1,           14, 15 ; $C7
map_const ROCKET_HIDEOUT_2,           14, 15 ; $C8
map_const ROCKET_HIDEOUT_3,           14, 15 ; $C9
map_const ROCKET_HIDEOUT_4,           12, 15 ; $CA
map_const ROCKET_HIDEOUT_ELEVATOR,     4,  3 ; $CB
map_const UNUSED_MAP_CC,               0,  0 ; $CC
map_const UNUSED_MAP_CD,               0,  0 ; $CD
map_const UNUSED_MAP_CE,               0,  0 ; $CE
map_const SILPH_CO_2F,                 9, 15 ; $CF
map_const SILPH_CO_3F,                 9, 15 ; $D0
map_const SILPH_CO_4F,                 9, 15 ; $D1
map_const SILPH_CO_5F,                 9, 15 ; $D2
map_const SILPH_CO_6F,                 9, 13 ; $D3
map_const SILPH_CO_7F,                 9, 13 ; $D4
map_const SILPH_CO_8F,                 9, 13 ; $D5
map_const MANSION_2,                  14, 15 ; $D6
map_const MANSION_3,                   9, 15 ; $D7
map_const MANSION_4,                  14, 15 ; $D8
map_const SAFARI_ZONE_EAST,           13, 15 ; $D9
map_const SAFARI_ZONE_NORTH,          18, 20 ; $DA
map_const SAFARI_ZONE_WEST,           13, 15 ; $DB
map_const SAFARI_ZONE_CENTER,         13, 15 ; $DC
map_const SAFARI_ZONE_REST_HOUSE_1,    4,  4 ; $DD
map_const SAFARI_ZONE_SECRET_HOUSE,    4,  4 ; $DE
map_const SAFARI_ZONE_REST_HOUSE_2,    4,  4 ; $DF
map_const SAFARI_ZONE_REST_HOUSE_3,    4,  4 ; $E0
map_const SAFARI_ZONE_REST_HOUSE_4,    4,  4 ; $E1
map_const UNKNOWN_DUNGEON_2,           9, 15 ; $E2
map_const UNKNOWN_DUNGEON_3,           9, 15 ; $E3
map_const UNKNOWN_DUNGEON_1,           9, 15 ; $E4
map_const NAME_RATERS_HOUSE,           4,  4 ; $E5
map_const CERULEAN_HOUSE_2,            4,  4 ; $E6
map_const UNUSED_MAP_E7,               0,  0 ; $E7
map_const ROCK_TUNNEL_2,              18, 20 ; $E8
map_const SILPH_CO_9F,                 9, 13 ; $E9
map_const SILPH_CO_10F,                9,  8 ; $EA
map_const SILPH_CO_11F,                9,  9 ; $EB
map_const SILPH_CO_ELEVATOR,           2,  2 ; $EC
map_const UNUSED_MAP_ED,               0,  0 ; $ED
map_const UNUSED_MAP_EE,               0,  0 ; $EE
map_const TRADE_CENTER,                4,  5 ; $EF
map_const COLOSSEUM,                   4,  5 ; $F0
map_const UNUSED_MAP_F1,               0,  0 ; $F1
map_const UNUSED_MAP_F2,               0,  0 ; $F2
map_const UNUSED_MAP_F3,               0,  0 ; $F3
map_const UNUSED_MAP_F4,               0,  0 ; $F4
map_const LORELEIS_ROOM,               6,  5 ; $F5
map_const BRUNOS_ROOM,                 6,  5 ; $F6
map_const AGATHAS_ROOM,                6,  5 ; $F7
