INCLUDE "macros/asm_macros.asm"
INCLUDE "macros/constants_macros.asm"

INCLUDE "constants/charmap.asm"

INCLUDE "ram/hram.asm"
INCLUDE "ram/vram.asm"

INCLUDE "constants/hardware_constants.asm"
INCLUDE "constants/oam_constants.asm"
INCLUDE "constants/misc_constants.asm"

INCLUDE "constants/pokemon_constants.asm"
INCLUDE "constants/trainer_constants.asm"
INCLUDE "constants/item_constants.asm"
INCLUDE "constants/type_constants.asm"
INCLUDE "constants/move_constants.asm"
INCLUDE "constants/move_animation_constants.asm"
INCLUDE "constants/move_effect_constants.asm"
INCLUDE "constants/status_constants.asm"
INCLUDE "constants/sprite_constants.asm"
INCLUDE "constants/palette_constants.asm"
INCLUDE "constants/evolution_constants.asm"
INCLUDE "constants/growth_rate_constants.asm"
INCLUDE "constants/list_constants.asm"
INCLUDE "constants/map_constants.asm"
INCLUDE "constants/connection_constants.asm"
INCLUDE "constants/hide_show_constants.asm"
INCLUDE "constants/credits_constants.asm"
INCLUDE "constants/music_constants.asm"
INCLUDE "constants/tilesets.asm"
INCLUDE "constants/starter_mons.asm"
INCLUDE "constants/event_constants.asm"
INCLUDE "constants/text_constants.asm"

INCLUDE "color/ram/wram.asm"
INCLUDE "color/constants/map_palette_constants.asm"
INCLUDE "color/constants/sprite_palette_constants.asm"

INCLUDE "macros/audio_macros.asm"
INCLUDE "macros/color_macros.asm"
INCLUDE "macros/data_macros.asm"
INCLUDE "macros/engine_macros.asm"
INCLUDE "macros/map_macros.asm"
INCLUDE "macros/event_macros.asm"
INCLUDE "macros/ram_macros.asm"
INCLUDE "macros/text_macros.asm"
