INCLUDE "macros/asm_macros.asm"

INCLUDE "macros/audio_macros.asm"
INCLUDE "macros/color_macros.asm"
INCLUDE "macros/constants_macros.asm"
INCLUDE "macros/data_macros.asm"
INCLUDE "macros/engine_macros.asm"
INCLUDE "macros/map_macros.asm"
INCLUDE "macros/event_macros.asm"
INCLUDE "macros/ram_macros.asm"
INCLUDE "macros/text_macros.asm"
