TrainerNames:
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "JR.TRAINER♂@"
	db "JR.TRAINER♀@"
	db "POKéMANIAC@"
	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "SWIMMER♀@"
	db "FISHERMAN@"
	db "SWIMMER♂@"
	db "CUE BALL@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "ROCKER@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BLACK BELT@"
	db "RIVAL1@"
	db "PROF.OAK@"
	db "ROCKET♀@"
	db "SCIENTIST@"
	db "GIOVANNI@"
	db "ROCKET♂@"
	db "ACE TRAINER♂@" ; COOLTRAINER_M
	db "ACE TRAINER♀@" ; COOLTRAINER_F
	db "BRUNO@"
	db "BROCK@"
	db "MISTY@"
	db "LT.SURGE@"
	db "ERIKA@"
	db "KOGA@"
	db "BLAINE@"
	db "SABRINA@"
	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "LORELEI@"
	db "MEDIUM@" ; CHANNELER
	db "AGATHA@"
	db "LANCE@"
